TrocaManuais.Web/Controllers/CatalogoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrocaManuais.Web.Models;
using PagedList;
using PagedList.Mvc;
using GridMvc.Html;

namespace TrocaManuais.Web.Controllers
{
    public class CatalogoController : Controller
    {

        private TrocamanuaisEntities db = new TrocamanuaisEntities();
        // GET: Catalogo
        public ActionResult Catalogo(int? page)
        {
            var manuais = db.manuais.Include(m => m.AnosEscolares).Include(m => m.Disciplinas).Include(m => m.Editoras).OrderBy(m=>m.ISBN);
            var pageNumber = page ?? 1;
            var onePageOfProducts = manuais.ToPagedList(pageNumber, 8);
            ViewBag.OnePageOfProducts = onePageOfProducts;
            return View(onePageOfProducts);
        }

        public ActionResult CatalogoPorAno(int? page,string EscalaoEscola)
        {
            DAL.Manuais.DLManuais IDAM = new DAL.Manuais.DLManuais(db);
            var manuais = IDAM.manuaisporescalao(EscalaoEscola);
            var pageNumber = page ?? 1;
            var onePageOfProducts = manuais.ToPagedList(pageNumber, 8);
            ViewBag.OnePageOfProducts = onePageOfProducts;
            return View(onePageOfProducts);
        }

        
        public ViewResult CatalogoAnoDisciplina(int? page, string AnoEscola, string disc)
        {
            DAL.Manuais.DLManuais IDAM = new DAL.Manuais.DLManuais(db);
            ViewBag.disc = new SelectList(db.Disciplinas, "disciplina", "disciplina");
            ViewBag.AnoEscola = new SelectList(db.AnosEscolares, "Ano", "ano");
          
            var manuais = IDAM.manuaisporDisciplinaAno(AnoEscola,disc).ToList();
            var pageNumber = page ?? 1;
            var onePageOfProductst = manuais.ToPagedList(pageNumber, 8);
            ViewBag.OnePageOfProducts = onePageOfProductst;
            return View(onePageOfProductst);
        }

        public ActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            manuais manuais = db.manuais.Find(id);
            if (manuais == null)
            {
                return HttpNotFound();
            }
            return View(manuais);
        }


        public ActionResult CatalogoEstabelecimentos(int? page, string estab, string Anol)
        {
            DAL.Pesquisa.pesquisas Pesq = new DAL.Pesquisa.pesquisas(db);
            ViewBag.Agrup = new SelectList(db.Agrupamentos, "agrupamento", "agrupamento");
            ViewBag.Estab = new SelectList(db.estabelecimentos, "design", "design");
            ViewBag.Anol = new SelectList(db.ALetivo,"Aletivo1","Aletivo1");
            var PesqMan = Pesq.manuaisporEstabelecimento(estab,Anol).ToList();
            var pageNumber = page ?? 1;
            var onePageOfProducts = PesqMan.ToPagedList(pageNumber, 8);
            ViewBag.OnePageOfProducts = onePageOfProducts;
            return View(onePageOfProducts);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult LoadEstabs(string idAgrup)
        {
            DAL.Pesquisa.pesquisas Pesq = new DAL.Pesquisa.pesquisas(db);
            var modelList = Pesq.GetAllEstabByAgrupID(Convert.ToInt32(idAgrup));
            var modelData = modelList.Select(m => new SelectListItem()
            {
                Text = m.design,
                Value = m.idestab.ToString(),

            });

            return Json(modelData, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CatalogoManuaisStock(int? page, string isbn)
        {
            DAL.Manuais.DLManuais PesqIsbn = new DAL.Manuais.DLManuais(db);
            var IsbnFind = PesqIsbn.GetManualEmStock(isbn).ToList();
            var pageNumber = page ?? 1;
            var onePageOfProducts = IsbnFind.ToPagedList(pageNumber, 8);
            ViewBag.OnePageOfProducts = onePageOfProducts;
            return View(onePageOfProducts);
        }


    }
}

TrocaManuais.Web/Views/CataLogo/CatalogoAnoDisciplina.cshtml
@model IEnumerable<TrocaManuais.Web.Models.TodosManuais>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using PagedList.Mvc;
@using PagedList;
@using System.Web.Mvc.Ajax;
@Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.js")

<link href="/Content/PagedList.css" rel="stylesheet" type="text/css" />
<h2>Catalogo de Manuais Escolares</h2>

<div class="container" id="TabCat">
    <div class="spanLeft">
        <table>
            <tr>
                @{int crow = 1;

                foreach (var item in Model)
                {
                    <td>
                        <ul>
                            <p>
                                <a href="@Url.Content(item.foto)">
                                    <img src="@Url.Content(item.foto)" alt="Image" height="300" width="200" />
                                </a>
                            </p>

                            <p>
                                @Html.DisplayNameFor(model => model.ISBN)
                                @Html.DisplayFor(modelItem => item.ISBN)
                            </p>
                            <p>
                                @Html.DisplayNameFor(model => model.titulo)
                                @Html.DisplayFor(modelItem => item.titulo)
                            </p>
                            <p>
                                @Html.DisplayNameFor(model => model.ano)
                                @Html.DisplayFor(modelItem => item.ano)
                            </p>
                            <p>
                                @Html.DisplayNameFor(model => model.disciplina)
                                @Html.DisplayFor(modelItem => item.disciplina)
                            </p>
                            <p>
                                @Html.DisplayNameFor(model => model.editora)
                                @Html.DisplayFor(modelItem => item.editora)
                            </p>
                            <p>
                                @Html.ActionLink("Detalhes do Manual", "Detalhes", new { id = item.idmanual })
                            </p>
                        </ul>
                    </td>
                    if (crow % 3 == 0)
                    {
                    <tr>
                        <td></td>
                    </tr>
                    }
                    crow++;
                }
                }
            </table>
           
        </div>
    <div class="spanRight">
        @using (Html.BeginForm("CatalogoAnoDisciplina", "Catalogo", FormMethod.Get))
        {
            <div class="form-group">
                Disciplina
                <div class="col-md-12">
                    @Html.DropDownList("disc", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                Ano
                <div class="col-md-12">
                    @Html.DropDownList("AnoEscola", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    <input type="submit" value="Pesquisa" />
                    </div>
                </div>
        }

    </div>
    </div>
    @Html.PagedListPager((IPagedList)ViewBag.OnePageOfProducts, page => Url.Action("CatalogoAnoDisciplina", new { page = page, foo = "bar" }))
    
        

TrocaManuais.Web/Views/CataLogo/CatalogoEstabelecimentos.cshtml
@model IEnumerable<TrocaManuais.Web.Models.ManuaisEstabelecimentos>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using PagedList.Mvc;
@using PagedList;

<script>
    $('#agrup').on('change',function()
    {
        var AgrupId = $(this).val();
        var CatalogoEstabelecimentosUrl = document.getElementById("CatalogoEstabelecimentos").value;
        if (CatalogoEstabelecimentosUrl == "") CatalogoEstabelecimentosUrl = "~/catalogo/catalogoestabelecimentos";
        $.when(loadEstabDropDown(AgrupId)
            .done(function(){
                console.log('Informação carregada com sucesso.');
            })
            .fail(function(){
                console.log('Não foi possivel carregar a informação. Por Favor seleccione correctamente');
            }));
    });
    function loadEstabDropDown(AgrupId)
    {
        $.getJSON('@Url.Action("LoadEstabs","Catalogo")', { AgrupId: AgrupId },function (response){
            $('#estab').empty();
            $('#estab').append($('<option>',{value:'',text:'Escolha o estabelecimento'}));
            $.each(response,function(key,value){
                $("#estab").append($('</option><option>'),{
                    value:value.Value,
                    text:value.text
                });
            });
        });
    }
    </option>
</script>
<link href="/Content/PagedList.css" rel="stylesheet" type="text/css" />

<h2>Catalogo de Manuais Escolares Adotados</h2>
<div class="container">
    @using (Html.BeginForm("CatalogoEstabelecimentos", "Catalogo", FormMethod.Get))
    {
        <table>
            <tr>
                <td>
                    <div class="form-group">
                        Estabelecimento
                        <div class="col-md-11">
                            @Html.DropDownList("estab", null, htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        Ano
                        <div class="col-md-12">
                          @Html.DropDownList("Anol", null, htmlAttributes: new { @class = "form-control" })  
                        </div>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                        <div class="col-md-11">
                            <p> </p>
                            <input type="submit" value="Pesquisa" />
                        </div>
                    </div>
                </td>
            </tr>
        </table>
    }
    <hr size="1" >
    <table class="gallery">
        <tr>
            @{int crow = 1;

            foreach (var item in Model)
            {
                <td>
                    <ul>
                        <p>
                            <a href="@Url.Content(item.foto)">
                                <img src="@Url.Content(item.foto)" alt="Image" height="300" width="200" />
                            </a>
                        </p>

                        <p>
                            @Html.DisplayNameFor(model => model.isbn)
                            @Html.DisplayFor(modelItem => item.isbn)
                        </p>
                        <p>
                            @Html.DisplayNameFor(model => model.titulo)
                            @Html.DisplayFor(modelItem => item.titulo)
                        </p>
                        <p>
                            @Html.DisplayNameFor(model => model.Ano)
                            @Html.DisplayFor(modelItem => item.Ano)
                        </p>
                        <p>
                            @Html.DisplayNameFor(model => model.disciplina)
                            @Html.DisplayFor(modelItem => item.disciplina)
                        </p>
                        <p>
                            @Html.DisplayNameFor(model => model.Editora)
                            @Html.DisplayFor(modelItem => item.Editora)
                        </p>
                        <p>
                            @Html.ActionLink("Detalhes do Manual", "Detalhes", new { id = item.idmanual })
                        </p>
                        <p>
                            @Html.ActionLink("Procura", "CatalogoManuaisStock","Catalogo",null, new { id = item.idmanual })
                        </p>
                    </ul>
                </td>
                if (crow % 4 == 0)
                {
                <tr>
                    <td></td>
                </tr>
                }
                crow++;
            }
            }

        </table>
    </div>

    @Html.PagedListPager((IPagedList)ViewBag.OnePageOfProducts, page => Url.Action("CatalogoPorAno", new { page = page, foo = "bar" }))

TrocaManuais.Web/Views/CataLogo/CatalogoManuaisStock.cshtml
@model IEnumerable<TrocaManuais.Web.Models.ManuaisEmStock>

@{
    ViewBag.Title = "Manuais Em Stock";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using PagedList.Mvc;
@using PagedList;

<link href="/Content/PagedList.css" rel="stylesheet" type="text/css" />

<h2>Manuais em Stock</h2>
<hr />
@using (Html.BeginForm())
{
    <table class="gallery">
        <tr>
            @{int crow = 1;

            foreach (var item in Model)
            {
                <td>
                    <ul>
                        <p>
                            <a href="@Url.Content(item.foto)">
                                <img src="@Url.Content(item.foto)" alt="Image" height="245" width="200" />
                            </a>
                        </p>

                        <p>
                            @Html.DisplayNameFor(model => model.ISBN)
                            @Html.DisplayFor(modelItem => item.ISBN)
                        </p>
                        <p>
                            @Html.DisplayNameFor(model => model.titulo)
                            @Html.DisplayFor(modelItem => item.titulo)
                        </p>
                        <p>
                            @Html.DisplayNameFor(model => model.ano)
                            @Html.DisplayFor(modelItem => item.ano)
                        </p>
                        <p>
                            @Html.DisplayNameFor(model => model.disciplina)
                            @Html.DisplayFor(modelItem => item.disciplina)
                        </p>
                        <p>
                            @Html.DisplayNameFor(model => model.editora)
                            @Html.DisplayFor(modelItem => item.editora)
                        </p>
                        <p>
                            @Html.DisplayNameFor(model => model.nick)
                            @Html.DisplayFor(modelItem => item.nick)
                        </p>
                        <p>
                            @Html.ActionLink("Contactar Utilizador", "Detalhes", new { id = item.ISBN })
                        </p>
                    </ul>
                </td>
                if (crow % 4 == 0)
                {
                <tr>
                    <td></td>
                </tr>
                }
                crow++;
            }
            }

        </table>
}
@Html.PagedListPager((IPagedList)ViewBag.OnePageOfProducts, page => Url.Action("CatalogoManuaisStock", new { page = page, foo = "bar" }))

TrocaManuais.Web/Views/CataLogo/CatalogoPorAno.cshtml
@model IEnumerable<TrocaManuais.Web.Models.TodosManuais>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using PagedList.Mvc;
@using PagedList;

<link href="/Content/PagedList.css" rel="stylesheet" type="text/css" />

<h2>Catalogo de Manuais Escolares</h2>
<hr />
@using (Html.BeginForm())
{
    <table class="gallery">
        <tr>
            @{int crow = 1;

            foreach (var item in Model)
            {
                <td>
                    <ul>
                        <p>
                            <a href="@Url.Content(item.foto)">
                                <img src="@Url.Content(item.foto)" alt="Image" height="245" width="200" />
                            </a>
                        </p>

                        <p>
                            @Html.DisplayNameFor(model => model.ISBN)
                            @Html.DisplayFor(modelItem => item.ISBN)
                        </p>
                        <p>
                            @Html.DisplayNameFor(model => model.titulo)
                            @Html.DisplayFor(modelItem => item.titulo)
                        </p>
                        <p>
                            @Html.DisplayNameFor(model => model.ano)
                            @Html.DisplayFor(modelItem => item.ano)
                        </p>
                        <p>
                            @Html.DisplayNameFor(model => model.disciplina)
                            @Html.DisplayFor(modelItem => item.disciplina)
                        </p>
                        <p>
                            @Html.DisplayNameFor(model => model.editora)
                            @Html.DisplayFor(modelItem => item.editora)
                        </p>
                        <p>
                            @Html.ActionLink("Detalhes do Manual", "Detalhes", new { id = item.idmanual })
                        </p>
                    </ul>
                </td>
                if (crow % 4 == 0)
                {
                <tr>
                    <td></td>
                </tr>
                }
                crow++;
            }
            }

        </table>
}
@Html.PagedListPager((IPagedList)ViewBag.OnePageOfProducts, page => Url.Action("CatalogoPorAno", new { page = page, foo = "bar" }))

TrocaManuais.Web/Views/CataLogo/Detalhes.cshtml
@model TrocaManuais.Web.Models.manuais

@{
    ViewBag.Title = "Detalhes";
    <!--Layout = "~/Views/Shared/_Layout.cshtml";-->
}

<h2>@Html.DisplayFor(model => model.titulo)</h2>

<div style="color:#80BFFF">
    <!--<hr />-->
    <dl class="dl-horizontal">
        <div class="row">
            <dl class="span4">
                <!--<dt>
                    @Html.DisplayNameFor(model => model.foto)
                </dt>-->
                <dd>
                    <!--<a href="@Url.Content(Model.foto)">-->
                        <img src="@Url.Content(Model.foto)" alt="Image" height="300" width="200" />
                    <!--</a>-->
                </dd>

            </dl>
            <dl class="span4">
                <dt>
                    ISBN
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ISBN)
                </dd>
                <dt>
                    Autores
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Autores)
                </dd>
                <p> </p>
                <dt>
                    Ano
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.AnosEscolares.Ano)
                </dd>
                <p> </p>
                <dt>
                    Disciplina
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Disciplinas.disciplina)
                </dd>
                <p> </p>
                <dt>
                    Editora
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Editoras.Editora)
                </dd>
                <p> </p>
                <dt>
                    <p> </p>
                </dt>
                <dd>
                    <button type="reset" class="medium orange"><i class="icon-undo"></i> Procurar Manual</button>
                </dd>
            </dl>
        </div>
    </dl>
</div>

<p>
    @Html.ActionLink("Back to List", "CatalogoPorAno", new { EscalaoEscola = "1º Ciclo" })
</p>

TrocaManuais.Web/Views/CataLogo/catalogo.cshtml
@model IEnumerable<TrocaManuais.Web.Models.manuais>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using PagedList.Mvc;  
@using PagedList;

<link href="/Content/PagedList.css" rel="stylesheet" type="text/css" />

<h2>Catalogo de Manuais Escolares</h2>

@using (Html.BeginForm())
{
    <table class="gallery">
        <tr>
            @{int crow = 1;
              
    foreach (var item in Model)
    {
        <td >
            <ul>
                <p>
                    <a href="@Url.Content(item.foto)">
                        <img src="@Url.Content(item.foto)" alt="Image" height="300" width="200" />
                    </a>
                </p>

                <p>
                    ISBN       :
                    @Html.DisplayFor(modelItem => item.ISBN)
                </p>
                <p>
                    TITULO     :
                    @Html.DisplayFor(modelItem => item.titulo)
                </p>
                <p>
                    ANO        : 
                    @Html.DisplayFor(modelItem => item.AnosEscolares.Ano)
                </p>
                <p>
                    DISCIPLINA :
                    @Html.DisplayFor(modelItem => item.Disciplinas.disciplina)
                </p>
                <p>
                    EDITORA    :
                    @Html.DisplayFor(modelItem => item.Editoras.Editora)
                </p>
                <p>
                    @Html.ActionLink("Detalhes do Manual", "Details", new { id = item.idmanual })
                </p>
             </ul>
</td>
        if (crow % 4 == 0)
        {
        <tr>
            <td></td>
        </tr>
        }
        crow++;
    }
            }
           
  </table>
}
@Html.PagedListPager((IPagedList)ViewBag.OnePageOfProducts, page => Url.Action("Catalogo", new { page = page, foo = "bar" }))